name: quelea
version: '2024.1'
base: core20
summary: Church projection software
description: |
  Quelea is a free and open source software application that projects
  multimedia content in your church service.
confinement: strict
issues: https://github.com/quelea-projection/Quelea/issues
license: GPL-3.0
grade: devel

environment:
    JAVA_HOME: $SNAP/jar/jvm
    PATH: $SNAP/jar/jvm/bin:$PATH
    
architectures:
  - build-on: [amd64]

apps:
  quelea:
    command: jar/launch.sh
    plugs: [home, mount-observe, network-control, network, network-bind, x11, wayland, unity7, opengl, optical-drive, alsa, pulseaudio, desktop, desktop-legacy, removable-media, gsettings, account-control]

parts:
  quelea:
    plugin: nil
    source: Quelea
    build-packages: [unzip, wget, gstreamer1.0-plugins-base, gstreamer1.0-plugins-good, gstreamer1.0-plugins-bad, gstreamer1.0-plugins-ugly, gstreamer1.0-libav, gstreamer1.0-tools, gstreamer1.0-x, gstreamer1.0-alsa, gstreamer1.0-gl, gstreamer1.0-gtk3, gstreamer1.0-qt5, gstreamer1.0-pulseaudio, zlib1g, zlib1g-dev]
    stage-packages: [gstreamer1.0-plugins-base, gstreamer1.0-plugins-good, gstreamer1.0-plugins-bad, gstreamer1.0-plugins-ugly, gstreamer1.0-libav, gstreamer1.0-tools, gstreamer1.0-x, gstreamer1.0-alsa, gstreamer1.0-gl, gstreamer1.0-gtk3, gstreamer1.0-qt5, gstreamer1.0-pulseaudio, zlib1g, zlib1g-dev]
    override-build: |
      wget https://cdn.azul.com/zulu/bin/zulu17.48.15-ca-fx-jdk17.0.10-linux_x64.tar.gz
      tar -xf zulu17.48.15-ca-fx-jdk17.0.10-linux_x64.tar.gz
      wget https://services.gradle.org/distributions/gradle-8.6-bin.zip
      unzip gradle-8.6-bin.zip
      PATH=$PATH:$(pwd)/zulu17.48.15-ca-fx-jdk17.0.10-linux_x64/bin:$(pwd)/gradle-8.6/bin
      JAVA_HOME=$(pwd)/zulu17.48.15-ca-fx-jdk17.0.10-linux_x64
      gradle -Djava.net.useSystemProxies=true -Dnightly=true -Dversionsuffix=CI-UNSTABLE clean downloadJres jar downloadUbuntuJvm copyToDist
    override-stage: |
      snapcraftctl stage
      cp -a /build/quelea/parts/quelea/build/dist/. $SNAPCRAFT_STAGE/jar
    override-prime: |
      snapcraftctl prime
      mkdir $SNAPCRAFT_PRIME/jar
      cp -a $SNAPCRAFT_STAGE/jar/. $SNAPCRAFT_PRIME/jar/.
      chmod +x $SNAPCRAFT_PRIME/jar/launch.sh
      rm -rf $SNAPCRAFT_PRIME/jar/winjre64
      ls -l $SNAPCRAFT_PRIME
      ls -l $SNAPCRAFT_PRIME/jar
      
      
