name: quelea
version: '2024.1'
base: core22
summary: Church projection
description: |
  Quelea is a free and open source software application that projects
  multimedia content in your church service.
confinement: strict

environment:
    JAVA_HOME: $SNAP/jar/jvm
    PATH: $SNAP/jar/jvm/bin:$PATH
    
architectures:
  - build-on: [amd64]

apps:
  quelea:
    command: sh $SNAP/jar/launch.sh
    plugs: [home, mount-observe, network-control, network, network-bind, x11, wayland, unity7, opengl, optical-drive, alsa, pulseaudio, desktop, desktop-legacy, removable-media, gsettings, account-control]

parts:
  quelea:
    plugin: nil
    source: Quelea
#    override-prime: |
#      snapcraftctl prime
#      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
    build-packages: [unzip, wget, gstreamer1.0-plugins-base, gstreamer1.0-plugins-good, gstreamer1.0-plugins-bad, gstreamer1.0-plugins-ugly, gstreamer1.0-libav, gstreamer1.0-tools, gstreamer1.0-x, gstreamer1.0-alsa, gstreamer1.0-gl, gstreamer1.0-gtk3, gstreamer1.0-qt5, gstreamer1.0-pulseaudio, zlib1g, zlib1g-dev]
    stage-packages: [unzip, wget, gstreamer1.0-plugins-base, gstreamer1.0-plugins-good, gstreamer1.0-plugins-bad, gstreamer1.0-plugins-ugly, gstreamer1.0-libav, gstreamer1.0-tools, gstreamer1.0-x, gstreamer1.0-alsa, gstreamer1.0-gl, gstreamer1.0-gtk3, gstreamer1.0-qt5, gstreamer1.0-pulseaudio, zlib1g, zlib1g-dev]
    override-build: |
      wget https://cdn.azul.com/zulu/bin/zulu21.32.17-ca-fx-jdk21.0.2-linux_x64.tar.gz
      tar -xf zulu21.32.17-ca-fx-jdk21.0.2-linux_x64.tar.gz
      wget https://services.gradle.org/distributions/gradle-8.6-bin.zip
      unzip gradle-8.6-bin.zip
      ls -l
      PATH=$PATH:$(pwd)/zulu21.32.17-ca-fx-jdk21.0.2-linux_x64/bin:$(pwd)/gradle-8.6/bin
      JAVA_HOME=$(pwd)/zulu21.32.17-ca-fx-jdk21.0.2-linux_x64
      ls -l zulu21.32.17-ca-fx-jdk21.0.2-linux_x64
      ls -l zulu21.32.17-ca-fx-jdk21.0.2-linux_x64/bin
      ls -l gradle-8.6
      ls -l gradle-8.6/bin
      echo $JAVA_HOME
      echo $PATH
      gradle --debug -Dnightly=true -Dversionsuffix=CI-UNSTABLE clean jar downloadUbuntuJvm copyToDist
#    gradle-openjdk-version: "21"
#    gradle-options: [--debug, -Dnightly=true, -Dversionsuffix=CI-UNSTABLE, clean, jar, downloadUbuntuJvm, copyToDist]
#    gradle-output-dir: 'dist'
