name: Master updated

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xB1998361219BD9C9
          curl -O https://cdn.azul.com/zulu/bin/zulu-repo_1.0.0-2_all.deb
          sudo apt-get install ./zulu-repo_1.0.0-2_all.deb
          sudo apt-get update
          sudo apt-get install zulu-fx-11
      - name: Environment setup
        run: |
          sudo apt install -y wine xvfb
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd Quelea
          chmod +x gradlew
          chmod +x build-install.sh
          wget http://files.jrsoftware.org/is/5/innosetup-5.6.1.exe
          wineboot --update
          Xvfb :0 -screen 0 1024x768x16 &
          DISPLAY=:0.0 wine innosetup-5.6.1.exe /VERYSILENT /SUPPRESSMSGBOXES
          "./gradlew -Dnightly=true -Dversionsuffix=CI-UNSTABLE clean dist"
