jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Environment setup
        run: |
          sudo apt install -y wine xvfb oraclejdk11
      - name: Checkout
        uses: actions/checkout@v4
        run: |
          cd Quelea
          chmod +x gradlew
          chmod +x build-install.sh
          wget http://files.jrsoftware.org/is/5/innosetup-5.6.1.exe
          wineboot --update
          Xvfb :0 -screen 0 1024x768x16 &
          DISPLAY=:0.0 wine innosetup-5.6.1.exe /VERYSILENT /SUPPRESSMSGBOXES
          "./gradlew -Dnightly=true -Dversionsuffix=CI-UNSTABLE clean dist"
