name: Master updated

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        run: |
          sudo apt-get -q update
          sudo apt-get -yq install gnupg curl
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xB1998361219BD9C9
          curl -O https://cdn.azul.com/zulu/bin/zulu11.68.17-ca-fx-jdk11.0.21-linux_amd64.deb
          sudo apt-get -y install ./zulu11.68.17-ca-fx-jdk11.0.21-linux_amd64.deb
      - name: Environment setup
        run: |
          sudo apt install -y wine wine32 xvfb
#          dpkg --add-architecture i386 && apt-get update
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd Quelea
          chmod +x gradlew
          chmod +x build-install.sh
          wget http://files.jrsoftware.org/is/5/innosetup-5.6.1.exe
          wineboot --update
          Xvfb :0 -screen 0 1024x768x16 &
          DISPLAY=:0.0 wine innosetup-5.6.1.exe /VERYSILENT /SUPPRESSMSGBOXES
          "./gradlew -Dnightly=true -Dversionsuffix=CI-UNSTABLE clean dist"
