name: Master updated

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        run: |
          curl -O https://cdn.azul.com/zulu/bin/zulu11.68.17-ca-fx-jdk11.0.21-linux_amd64.deb
          sudo apt-get -y install ./zulu11.68.17-ca-fx-jdk11.0.21-linux_amd64.deb
      - name: Environment setup
        run: |
          sudo apt install -y wine xvfb
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install wine32
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        env:
          DISPLAY: :99
        run: |
          wget http://files.jrsoftware.org/is/5/innosetup-5.6.1.exe
          Xvfb $DISPLAY &
          wine wineboot --init
          echo "Installing INNOSETUP"
          wine innosetup-5.6.1.exe /VERYSILENT /SUPPRESSMSGBOXES
          cd Quelea
          chmod +x gradlew
          chmod +x build-install.sh
          ./gradlew -Dnightly=true -Dversionsuffix=CI-UNSTABLE clean dist
          ls -l
          ls -l dist/standalone